// Auto-generated NM name list (lower-case, sorted for binary search).
// Baked into the plugin so NM detection needs NO runtime dependency on any addon.
#ifndef TARGETAURA_NMNAMES_H
#define TARGETAURA_NMNAMES_H

static const char* const g_nmNames[] = {
    "aa xalmo the savage",
    "aa'bho slashburner",
    "abas",
    "abatwa",
    "absolute virtue",
    "abununnu",
    "abyss sahagin",
    "abyssdiver",
    "abyssic cluster",
    "ace of batons",
    "ace of coins",
    "ace of cups",
    "ace of swords",
    "achamoth",
    "achamothcampa",
    "acolnahuacatl",
    "adaman quadav",
    "adamantking image",
    "adamantoise",
    "adamastor",
    "adze",
    "aello",
    "aello's handmaiden",
    "agar agar",
    "agas",
    "agathos",
    "aggressor antlion",
    "agonizer",
    "agrios",
    "ah puch",
    "ahtu",
    "aiatar",
    "air elemental",
    "aither",
    "aitvaras",
    "akash",
    "akupara",
    "akvan",
    "alastor antlion",
    "albino antlion",
    "albumen's korrigan",
    "albumen's lycopodium",
    "albumen's pachypodium",
    "alectryon",
    "alfard",
    "alklha",
    "alkonost",
    "alkyoneus",
    "all-seeing onyx eye",
    "allied armored belfry",
    "allocamelus",
    "almighty apkallu",
    "almops",
    "alpine rabbit",
    "alpluachra",
    "alsha",
    "amaltheia",
    "amanita",
    "amaranth barrier",
    "amarok",
    "ambuscader antlion",
    "ambusher antlion",
    "amemet",
    "amhuluk",
    "amikiri",
    "amphiptere",
    "amphitrite",
    "amun",
    "amymone",
    "amymone's peapuk",
    "anantaboga",
    "ancestral rage",
    "ancient bombs",
    "ancient goobbue",
    "ancient vessel",
    "ancient weapon",
    "ancilla beetle",
    "angra mainyu",
    "angrboda",
    "anguis",
    "anhanguera",
    "animated claymore",
    "animated dagger",
    "animated great axe",
    "animated gun",
    "animated hammer",
    "animated horn",
    "animated knuckles",
    "animated kunai",
    "animated longbow",
    "animated longsword",
    "animated scythe",
    "animated shield",
    "animated spear",
    "animated staff",
    "animated tabar",
    "animated tachi",
    "anise custard",
    "ankabut",
    "ankou",
    "annihilative adenium",
    "ansherekh",
    "antaeus",
    "anthracite antlion",
    "antican consul",
    "antican legatus",
    "antican magister",
    "antican praefectus",
    "antican praetor",
    "antican proconsul",
    "antican tribunus",
    "anvilix sootwrists",
    "apademak",
    "apocalyptic beast",
    "aqrabuamelu",
    "aquarius",
    "arachne",
    "arboreal bastion",
    "arcane phantasm",
    "arch angra mainyu",
    "arch antaeus",
    "arch apocalyptic beast",
    "arch christelle",
    "arch dynamis lord",
    "arch goblin golem",
    "arch gu'dha effigy",
    "arch overlord tombstone",
    "arch tzee xicu idol",
    "arch-omega",
    "archaic chariot",
    "archaic gear",
    "archaic gears",
    "archaic rampart",
    "arcus blades",
    "argus",
    "arimaspi",
    "arioch",
    "ariri samariri",
    "ark angel's gnat",
    "arke",
    "armed gears",
    "armillaria",
    "armored chariot",
    "armored hunter",
    "aroma crawler",
    "aroma fly",
    "aroma leech",
    "asanbosam",
    "asb",
    "ascended beetle",
    "ascended chapuli",
    "ascended chigoe",
    "ascended cyhiraeth",
    "ascended faaz",
    "ascended gefyrst",
    "ascended hippogryph",
    "ascended lucani",
    "ascended luckybug",
    "ascended mantis",
    "ascended mosquito",
    "ascended naraka",
    "ascended panopt",
    "ascended poroggo",
    "ascended porxie",
    "ascended tiger",
    "ascended ungeweder",
    "ascetox ratgums",
    "ash dragon",
    "ashmaker gotblut",
    "ashtaerh the gallvexed",
    "asida",
    "asphyxiated amsel",
    "aspidochelone",
    "assailer chariot",
    "assassin's apprentice",
    "asterion",
    "astika",
    "at'euvhi",
    "athamas",
    "atkorkamuy",
    "audumbla",
    "auspicious entity",
    "australis shadow",
    "autarch",
    "avalerion",
    "avatar idol",
    "avian roost",
    "awahondo",
    "awd goggie",
    "axesarion the wanderer",
    "ayapec",
    "aynu-kaysey",
    "ayravata",
    "azdaja",
    "azi dahaka",
    "azi dahaka's dragon",
    "azrael",
    "azure-toothed clawberry",
    "ba'tho mercifulheart",
    "baa dava the bibliophage",
    "baba yaga",
    "backoo",
    "badshah",
    "bai hu",
    "bakka",
    "bakunawa",
    "balam-agab",
    "balam-quitz",
    "balamor",
    "balamor's sycophant",
    "balaur",
    "ballistosporer",
    "balor",
    "bandrix rockjaw",
    "banespore",
    "baobhan sith",
    "barakbok",
    "barbaric weapon",
    "barbastelle",
    "baron avnas",
    "baron vapula",
    "baronet romwe",
    "barong",
    "baronial bat",
    "barra edinazu",
    "bashe",
    "bashmu",
    "bastet",
    "battlechoir gitchfotch",
    "battleclad chariot",
    "battledressed chariot",
    "battlerigged chariot",
    "baumesel",
    "bayawak",
    "be'hya hundredwall",
    "be'zhe keeprazer",
    "bedraggled bale",
    "bedrock barry",
    "beet leafhopper",
    "begrimed bale",
    "behemoth",
    "belladonna",
    "belphegor",
    "belphoebe",
    "bendigeit vran",
    "bennu",
    "beorht",
    "berried chigoe",
    "berry syrup",
    "berstuk",
    "beryl-footed molberry",
    "bhishani",
    "bhumi",
    "bhuu wjato the firepool",
    "bi'gho headtaker",
    "bia",
    "biast",
    "big bang",
    "big bomb",
    "bigmouth billy",
    "bilopdop",
    "bisa",
    "bismarck",
    "bisque-heeled sunberry",
    "bistre-hearted malberry",
    "black coney",
    "black shuck",
    "black triple stars",
    "blackbeard",
    "bladeburner rokgevok",
    "blanga",
    "blazing eruca",
    "blazox boneybod",
    "blifnix oilycheeks",
    "blightdella",
    "blighting brand",
    "blind moby",
    "blobdingnag",
    "bloodeye vileberry",
    "bloodfist voshgrosh",
    "bloodguzzler",
    "bloodlapper",
    "bloodmoon umbril",
    "bloodpool vorax",
    "bloodsucker",
    "bloodswiller fly",
    "bloodtear baldurf",
    "bloodthirster madkix",
    "bloody bones",
    "bloody coffin",
    "bloody daggers",
    "bloody skull",
    "blubbery bulge",
    "blue bascinet",
    "bluestreak gyugyuroon",
    "bo'dho hundredfist",
    "bo'who warmonger",
    "bodach",
    "boggelmann",
    "boll weevil",
    "bolster",
    "bomb bastard",
    "bomb king",
    "bomb prince",
    "bomb princess",
    "bomb queen",
    "bombadeel",
    "bombast",
    "bomblix flamefinger",
    "bompupu",
    "bonnacon",
    "bonze marberry",
    "boobrie",
    "boompadu",
    "bootrix jaggedelbow",
    "bordox kittyback",
    "boreal coeurl",
    "boreal hound",
    "boreal tiger",
    "borealis shadow",
    "boroka",
    "bothersome chapuli",
    "botulus rex",
    "bounding belinda",
    "brass borer",
    "brazen bones",
    "brekekekex",
    "bres",
    "brewnix bittypupils",
    "briareus",
    "brigandish blade",
    "bright-handed kunberry",
    "brooder",
    "brulo",
    "brummbar",
    "brummer",
    "bu'bho truesteel",
    "bu'ghi howlblade",
    "buarainech",
    "bubbly bernie",
    "buburimboo",
    "bucca",
    "buffrix eargone",
    "bugaboo",
    "bugallug",
    "bugbby",
    "bugbear matman",
    "bugbear muscleman",
    "bugbear porterman",
    "bugbear strongman",
    "bugul noz",
    "bukhis",
    "bukki",
    "bune",
    "burgeoning flames",
    "burlibix brawnback",
    "burned bergmann",
    "burstrox powderpate",
    "buu xolo the bloodfaced",
    "byakko",
    "caa xaza the madpiercer",
    "cactrot rapido",
    "cactrot veloz",
    "cactuar cantautor",
    "caedarva toad",
    "cait sith",
    "caithleann",
    "calcabrina",
    "calchas",
    "caldera crab",
    "calydontis",
    "camahueto",
    "came-cruse",
    "canal moocher",
    "cancer",
    "canis dirus",
    "cannered noz",
    "capricious cassie",
    "capricornus",
    "carabosse",
    "caraway custard",
    "carbuncle prime",
    "cargo crab colin",
    "carmine dobsonfly",
    "carmine-tailed janberry",
    "carnero",
    "carousing celine",
    "carrion dragon",
    "carthi",
    "cath palug",
    "cavanneche",
    "celaeno",
    "celeste-eyed tozberry",
    "celphie",
    "cemetery cherry",
    "centipedal centruroides",
    "centurio iv-vii",
    "centurio x-i",
    "centurio xii-i",
    "centurio xiii-v",
    "centurio xx-i",
    "cep-kamuy",
    "cerberus",
    "cerebrator",
    "cerise wasp",
    "cernunnos",
    "cetus",
    "chahnameed",
    "chamrosh",
    "chandelier",
    "chaneque",
    "chaos elemental",
    "chariotbuster byakzak",
    "chary apkallu",
    "charybdis",
    "chasmic hornet",
    "cheese hoarder gigiroon",
    "chekochuk",
    "chelicerata",
    "cherti",
    "cherufe",
    "cherukiki",
    "chesma",
    "chhir batti",
    "chickcharney",
    "chigoe's nit",
    "chigre",
    "chillwing hwitti",
    "chione",
    "chloris",
    "chocoboleech",
    "chonchon",
    "chorus toad",
    "chuglix berrypaws",
    "chukwa",
    "cinder crab",
    "cinderwing",
    "cinnamon custard",
    "cirein-croin",
    "cirrate christelle",
    "citadel chelonian",
    "citadel pipistrelles",
    "citipati",
    "claret",
    "climbpix highrise",
    "clingy clare",
    "cloktix longnail",
    "cloud of darkness",
    "cobalt quadav",
    "cobraclaw buchzvotch",
    "coca",
    "coeurl mystic",
    "coeurl prentice",
    "coeurl tiro",
    "cogtooth skagnogg",
    "coinbiter cjaknokk",
    "colorful leshy",
    "conflagrant eruca",
    "contantican black mage",
    "contantican paladin",
    "contantican ranger",
    "contantican warrior",
    "contumacious ovim",
    "coo keja the unseen",
    "cookieduster lipiroon",
    "copper borer",
    "coquecigrue",
    "coral sahagin",
    "counselor gadalar",
    "counselor najelith",
    "counselor rughadjeen",
    "counselor zazarg",
    "count bifrons",
    "count haagenti",
    "count raum",
    "count vine",
    "count zaebos",
    "coveter",
    "cowll hippogryph",
    "crabapple treant",
    "craklaw",
    "craven einherjar",
    "crimson eruca",
    "crimson grimoire",
    "crimson-toothed pawberry",
    "crom dubh",
    "croque-mitaine",
    "crushed krause",
    "crypt ghost",
    "cryptonberry assassin",
    "cryptonberry executor",
    "crystal eater",
    "crystal fetter",
    "cuelebre",
    "cuijatender",
    "cumin custard",
    "cumulator",
    "cunnast",
    "cunning craklaw",
    "cursed axe",
    "custom cardian",
    "cwn cyrff",
    "cyanic crab",
    "da'dha hundredmask",
    "dabotz's ghost",
    "daggerclaw dracos",
    "dagourmarche",
    "dahu",
    "dalham",
    "damask crab",
    "dame blanche",
    "dark elemental",
    "dark ixion",
    "dark rider",
    "dark spark",
    "darkness",
    "darting kachaal ja",
    "dawon",
    "dazzling dolores",
    "de'bho pyrohand",
    "de'vyu headhunter",
    "dea",
    "deadly dodo",
    "death clan destroyer",
    "death from above",
    "deathcaller bidfbid",
    "deathly stinger",
    "decurio i-iii",
    "decurio xiii-lv",
    "dee zelko the esoteric",
    "deelgeed",
    "defoliate leshy",
    "delicieuse delphine",
    "deloknok",
    "demoiselle desolee",
    "demonic rod",
    "demonic tiphia",
    "denn the orcavoiced",
    "deorc",
    "depths digester",
    "deranged ameretat",
    "dervo's ghost",
    "desmodont",
    "despot",
    "deviate bhoot",
    "deviator",
    "devout radol ja",
    "dextrose",
    "dhorme khimaira",
    "dhoul",
    "di'dha adamantfist",
    "di'zho spongeshell",
    "diabolos club",
    "diabolos diamond",
    "diabolos heart",
    "diabolos letum",
    "diabolos nox",
    "diabolos somnus",
    "diabolos spade",
    "diabolos umbra",
    "diabolos's vestige",
    "diamond daig",
    "diamond quadav",
    "dimensional tether",
    "dimgruzub",
    "diremite",
    "diremite dominator",
    "dirtyhanded gochakzuk",
    "disaster idol",
    "distilix stickytoes",
    "distraught draugar",
    "div-e sepid",
    "divagating jagil",
    "dog guardian",
    "doglix muttsnout",
    "doman",
    "donggu",
    "donnergugi",
    "doo peku the fleetfoot",
    "doomed pilgrims",
    "doppelganger dio",
    "doppelganger gog",
    "dorgerwor the astute",
    "dosetsu tree",
    "douma weapon",
    "dozing dorian",
    "dragonscaled bugaal ja",
    "dragua",
    "drakefeast wubmfub",
    "draketrader zlodgodd",
    "draklix scalecrust",
    "dreadbug",
    "drekavac",
    "drexerion the condemned",
    "dribblix greasemaw",
    "drone crawler",
    "drooling daisy",
    "droprix granitepalms",
    "drumskull zogdregg",
    "duke berith",
    "duke decapod",
    "duke focalor",
    "duke gomory",
    "duke haborym",
    "duke haures",
    "duke scox",
    "duke vepar",
    "duke vepar's gnat",
    "dune widow",
    "durinn",
    "duu masa the onecut",
    "duu nazo the spryfooted",
    "dvalinn",
    "dyinyinga",
    "dynamis lord",
    "dynast beetle",
    "ea'tho cruelheart",
    "earth elemental",
    "eastern shadow",
    "eba",
    "eccentric eve",
    "edacious opo-opo",
    "edifier",
    "edonus",
    "effigy prototype",
    "elatha",
    "eldhrimnir",
    "eldritch edge",
    "electrified yanthu",
    "elel",
    "elemental gyves",
    "elixmix hooknose",
    "ellylldan",
    "ellyllon",
    "elusive edwin",
    "elvaan automaton",
    "elvaanlopper grokdok",
    "elvaansticker bxafraff",
    "emela-ntouka",
    "emergent elm",
    "empathic flan",
    "emperador de altepa",
    "emperor arthro",
    "empousa",
    "emputa",
    "enagakure",
    "energetic eruca",
    "enkelados",
    "eorthe",
    "epialtes",
    "erebus",
    "eremix snottynostril",
    "ereshkigal",
    "erinys",
    "erle",
    "erupting geyser",
    "es'euvhi",
    "esoteric scrivening",
    "ethniu",
    "euryale",
    "eurymedon",
    "eurytos",
    "executioner antlion",
    "experimental lamia",
    "eyegouger",
    "eyy mon the ironbreaker",
    "faded craklaw",
    "fafnir",
    "fahrafahr the bloodied",
    "fairy ring",
    "falcatus aranei",
    "falsespinner bhudbrodd",
    "famished raaz",
    "fantoccini automaton",
    "farlarder the shrewd",
    "farruca fly",
    "father frost",
    "faust",
    "fear gorta",
    "feeblescheme bhogbigg",
    "feeler antlion",
    "feralox honeylips",
    "fervid funguar",
    "festering umbril",
    "feuerunke",
    "fire elemental",
    "fire pukis",
    "fired urn",
    "firedance magmaal ja",
    "fistule",
    "fjalar",
    "flamecaller zoeqdoq",
    "flames of muspelheim",
    "flammeri",
    "flauros",
    "fleshflayer killakriq",
    "fleshgnasher",
    "flockbock",
    "flux flan",
    "fomor pioneer",
    "fomorian spear",
    "foo peku the bloodcloak",
    "foreseer oramix",
    "forger",
    "fradubio",
    "fraelissa",
    "friar rush",
    "frightful funguar",
    "frogamander",
    "frost bomb mk-ii",
    "frost flambeau",
    "frostfang tiger",
    "frostmane",
    "fuath",
    "fulmotondro",
    "fulvous bats",
    "funereal apkallu",
    "fungus beetle",
    "furfluff lapinion",
    "furibund rafflesia",
    "furious arundmite",
    "fuu tzapo the blessed",
    "fyuu the seabellow",
    "ga'bhu unvanquished",
    "ga'fho venomtouch",
    "ga'lhu nevermolt",
    "gabblox magpietongue",
    "gaizkin",
    "gajasimha",
    "galkarider retzpratz",
    "gamayun",
    "gambilox wanderling",
    "gancanagh",
    "gangly gean",
    "garfurlar the rabid",
    "gargantua",
    "gargouille warden",
    "gargoyle-iota",
    "gargoyle-kappa",
    "gargoyle-lambda",
    "gargoyle-mu",
    "garharlor the unruly",
    "garhorlur the brutal",
    "gaunab",
    "gavotvut",
    "gawky gawain",
    "ge'dha evileye",
    "genbu",
    "gerwitz's axe",
    "gerwitz's scythe",
    "gerwitz's soul",
    "gerwitz's sword",
    "gestalt",
    "geush urvan",
    "geyser lizard",
    "gharial",
    "gherrmoga",
    "ghillie dhu",
    "gi'bhe fleshfeaster",
    "gi'ghi rockchopper",
    "gi'pha manameister",
    "giant moa",
    "gibberox pimplebeak",
    "gieremund",
    "gigaplasm",
    "gigas clearcutter",
    "gigas hillrazer",
    "giltine",
    "ginger custard",
    "girtablulu",
    "gizerl's ghost",
    "gjenganger",
    "glavoid",
    "glazemane",
    "gloam servitor",
    "globster",
    "gloom eye",
    "gloomanita",
    "gloombound lurker",
    "gloomtalon",
    "glyryvilu",
    "gnawtooth gary",
    "go'bha slaughterer",
    "go'bhu gascon",
    "go'bhu herohunter",
    "go'tyo magenapper",
    "goaftrap",
    "goblin archaeologist",
    "goblin collector",
    "goblin enforcer",
    "goblin golem",
    "goblin intimidator",
    "goblin picaroon",
    "goblin preceptor",
    "goblin repossessor",
    "goblin statue",
    "goblin wolfman",
    "goblinsavior heronox",
    "goblintrap",
    "goji",
    "goldcap",
    "golden bat",
    "golden kist",
    "golden-tongued culberry",
    "goliath",
    "goobbue wanderer",
    "gorattz",
    "gordov's ghost",
    "gorebeak",
    "gorehound",
    "gorge vulture",
    "gosspix blabberlips",
    "gotoh zha the redolent",
    "goublefaupe",
    "grand duke batym",
    "grand'goule",
    "grandgousier",
    "granite borer",
    "graoully",
    "gration",
    "greater amphiptere",
    "greater gnole",
    "greenman",
    "grenade syrup",
    "ground guzzler",
    "grwnan",
    "gu'dha effigy",
    "gu'dho staggershell",
    "gu'khu dukesniper",
    "gu'nha wallstormer",
    "gu'nhi noondozer",
    "guard hippogryph",
    "guardian crawler",
    "guardian statue",
    "guardian treant",
    "gudanna",
    "gugalanna",
    "guivre",
    "gukumatz",
    "gulool ja ja",
    "gurfurlur the menacing",
    "guu waji the preacher",
    "gwyllgi",
    "gwyn ap knudd",
    "gwynn ap nudd",
    "gyre-carlin",
    "gyroscopic gear",
    "gyroscopic gears",
    "haa pevi the stentorian",
    "habergoass",
    "habetrot",
    "habrok",
    "hadal mirror",
    "hadal satiator",
    "hadhayosh",
    "hahava",
    "hakawai",
    "hakutaku",
    "halimede",
    "hamfist gukhbuk",
    "hammerblow majanun",
    "hanbi",
    "hanbi's demon",
    "hanuman",
    "harpimaira",
    "harvestman",
    "hastatus xi-xii",
    "haty",
    "hawkeyed dnatbat",
    "hazhalm bat",
    "hazhalm bats",
    "hazhdiha",
    "hazmat",
    "heavenly veela",
    "heavymail djidzbad",
    "hedetet",
    "hedjedjet",
    "hee mida the meticulous",
    "heike crab",
    "heliodromos",
    "heliotrope barrier",
    "hell fly",
    "helldiver",
    "hellion",
    "hematic cyst",
    "hemodrosophila",
    "heqet",
    "herbage hunter",
    "hercules beetle",
    "herensugue",
    "hermitrix toothrot",
    "hexenpilz",
    "hidhaegg",
    "highlander lizard",
    "hilltroll elite guard",
    "hippocentaur",
    "hippolytos",
    "hippomaritimus",
    "hitaume",
    "hoar-knuckled rimberry",
    "holey horror",
    "holy moly",
    "honey fly",
    "honor",
    "hoo mjuu the torrent",
    "hovering hotpot",
    "hraun dragon",
    "hrosshvalur",
    "hugemaw harold",
    "humbaba",
    "hume automaton",
    "humegutter adzjbadj",
    "humnox drumbelly",
    "hundredfaced hapool ja",
    "hundredscar hajwaj",
    "hungerer",
    "hunting wasp",
    "huu xalmo the savage",
    "huwasi",
    "hyakinthos",
    "hyakume",
    "hydra",
    "ice elemental",
    "ichorous ire",
    "icon prototype",
    "ig-alima",
    "ignamoth",
    "ika-roa",
    "iktomi",
    "iku-turso",
    "ildebrann",
    "imdugud",
    "immanibugard",
    "immortal flan",
    "imperial gear",
    "imperial gears",
    "impervious chariot",
    "incandescent baelfyr",
    "incensed lucerewe",
    "incensed pineapple",
    "indich",
    "indomitable spurned",
    "indrik",
    "ingaevon",
    "inquisitor mortuus",
    "insidio",
    "intuila",
    "intulo",
    "ionos",
    "iqi-balam",
    "iratham",
    "iriri samariri",
    "iriz ima",
    "iron cranium",
    "ironbeak inguza",
    "ironclad animus",
    "ironclad cleaver",
    "ironclad executioner",
    "ironclad harbinger",
    "ironclad observer",
    "ironclad pulverizer",
    "ironclad severer",
    "ironclad smiter",
    "ironclad sunderer",
    "ironclad triturator",
    "ironclad vaporizer",
    "ironclad wrecker",
    "ironhorn baldurno",
    "ironside",
    "irrlicht",
    "isarukitsck",
    "isgebind",
    "isonade",
    "itzpapalotl",
    "ix'aern",
    "ix'ghrah",
    "ix'zdei",
    "ixtab",
    "jabbrox grannyguise",
    "jabkix pigeonpecs",
    "jack of batons",
    "jack of coins",
    "jack of cups",
    "jack of swords",
    "jaculus",
    "jaded jody",
    "jaggedy-eared jack",
    "jailer of faith",
    "jailer of fortitude",
    "jailer of hope",
    "jailer of justice",
    "jailer of love",
    "jailer of prudence",
    "jailer of temperance",
    "jala",
    "jammer leech",
    "jazaraat",
    "jebutoise",
    "jeduah",
    "jenglot",
    "jester malatrix",
    "jeunoraider gepkzip",
    "ji'fhu infiltrator",
    "ji'khu towercleaver",
    "jolly green",
    "jormungand",
    "jotunn ruffian",
    "jovial ahriman",
    "joyous green",
    "judgmental julika",
    "juggler hecatomb",
    "juu duzu the whirlwind",
    "juu zeni the poisonmist",
    "jyeshtha",
    "kabandha",
    "kadraeth the hatespawn",
    "kaggen",
    "kalasutrax",
    "kaliya",
    "kalos eunomia",
    "kammavaca",
    "kammavaca's amoeban",
    "kammavaca's clionid",
    "kammavaca's limule",
    "kammavaca's murex",
    "kamohoalii",
    "kampe",
    "kanavid",
    "kaneakeluh",
    "kappa akuso",
    "kappa biwa",
    "kappa bonze",
    "karashix swollenskull",
    "karkadann",
    "karkatakam",
    "katashiro weapon",
    "kee taw the nightingale",
    "keeper of halidom",
    "keeper of heiligtum",
    "keesha poppo",
    "kegpaunch doshgnosh",
    "keratyrannos",
    "ketea",
    "kettenkaefer",
    "kf'ghrah",
    "khalamari",
    "khalkotaur",
    "kharon",
    "khimaira",
    "kholomodumo",
    "khon",
    "khromasoul bhurborlor",
    "khun",
    "kikklix longlegs",
    "killer jonny",
    "killer korrigan",
    "kinepikwa",
    "king arthro",
    "king behemoth",
    "king goldemar",
    "king of batons",
    "king of coins",
    "king of cups",
    "king of swords",
    "king uropygid",
    "king vinegarroon",
    "king zagan",
    "kirata",
    "kirin",
    "kirlirger the abhorrent",
    "kirtimukha",
    "knii hoqo the bisector",
    "ko'dho cannonball",
    "koenigstiger",
    "koghatu",
    "koios",
    "konjac",
    "koo rahi the levinblade",
    "koo saxu the everfast",
    "koropokkur",
    "korroloka leech",
    "kotan-kor kamuy",
    "koura",
    "kouryu",
    "krabakarpo",
    "krabimanjaro",
    "krabkatoa",
    "kraken",
    "kreutzet",
    "ku'jhu graniteskin",
    "kukki-chebukki",
    "kukulkan",
    "kulili",
    "kumhau",
    "kur",
    "kurma",
    "kurrea",
    "kutharei",
    "kuu xuka the nimble",
    "la theine liege",
    "la velue",
    "lachrymater",
    "lacovie",
    "lacus",
    "lady lilith",
    "laelaps",
    "laidly laurence",
    "lamia no.19",
    "lamia no.27",
    "lamia no.9",
    "lamie no.7",
    "lamie no.8",
    "lamie no.9",
    "lamina",
    "lamprey lord",
    "lanky lenglen",
    "largantua",
    "larkish opo-opo",
    "larzos",
    "leaping lizzy",
    "leech king",
    "legalox heftyhind",
    "legendary weapon",
    "lentor",
    "lesath",
    "leshonki",
    "lesser arimaspi",
    "leucosia",
    "ligeia",
    "light elemental",
    "lightning gremlin",
    "lii jixa the somnolist",
    "likho",
    "lil' apkallu",
    "lilith ascendant",
    "lindwurm",
    "lioumere",
    "liquidbone leech",
    "liquified einherjar",
    "little wingman",
    "livid umbril",
    "lividroot amooshah",
    "living staves",
    "lizardtrap",
    "lobais",
    "lockbuster zapdjipp",
    "lode golem",
    "lofty adamantoise",
    "lofty behemoth",
    "lofty elasmoth",
    "lofty ferromantoise",
    "lofty harpeia",
    "lofty wyrm",
    "lofty zilant",
    "long-armed chariot",
    "long-barreled chariot",
    "long-bowed chariot",
    "long-gunned chariot",
    "long-horned chariot",
    "loo hepe the eyepiercer",
    "loo kutto the pensive",
    "lorbulcrud",
    "lord asag",
    "lord of onzozo",
    "lord ruthven",
    "lord varney",
    "lorelei",
    "lost aitvaras",
    "lost alklha",
    "lost barong",
    "lost fairy ring",
    "lost nant'ina",
    "lost scolopendra",
    "lost soul",
    "lost stcemqestcint",
    "lost stihi",
    "lost stringes",
    "lost suttung",
    "luaith",
    "lugarhoo",
    "lugh",
    "lumber jack",
    "lumbering lambert",
    "lunatic lycopodium",
    "lurklox dhalmelneck",
    "lusca",
    "lustful lydia",
    "lyncean juwgneg",
    "ma",
    "maa febi the steadfast",
    "maa illmu the bestower",
    "maa zaua the wyrmkeeper",
    "maahes",
    "macroplasm",
    "mad bomber",
    "madthrasher zradbodd",
    "maere",
    "magic shields",
    "magic sludge",
    "magma",
    "magnotaur",
    "maharaja",
    "mahisha",
    "mahishasura",
    "mahjlaef the paintorn",
    "maighdean uaine",
    "maju",
    "makki-chebukki",
    "malefic fencer",
    "malicious magpie",
    "malleator maurok",
    "maltha",
    "manananggal",
    "manes",
    "mangy-tailed marvin",
    "manipulator",
    "manohra",
    "marauder dvogzog",
    "marchelute",
    "mariselle's pupil",
    "marquis allocen",
    "marquis amon",
    "marquis andras",
    "marquis andrealphus",
    "marquis caim",
    "marquis cimeries",
    "marquis decarabia",
    "marquis forneus",
    "marquis gamygyn",
    "marquis naberius",
    "marquis nebiros",
    "marquis orias",
    "marquis sabnak",
    "marquis sabnock",
    "martinet",
    "masan",
    "mastop",
    "matamata",
    "matron crawler",
    "mauve-wristed gomberry",
    "meanderer",
    "meditator",
    "medusa",
    "mee deggi the punisher",
    "megalobugard",
    "megamaw mikey",
    "megantereon",
    "megapod megalops",
    "melancholic moira",
    "mellonia",
    "melo melo",
    "melusine",
    "memory receptacle",
    "menechme",
    "mephitas",
    "merrow no.5",
    "met",
    "metal shears",
    "meteormauler zhagtegg",
    "metus",
    "meww the turtlerider",
    "mi'ghrah",
    "mi'rhe whisperblade",
    "microplasm",
    "mictlantecuhtli",
    "mielikki",
    "migrant russula",
    "migratory hippogryph",
    "mikilulu",
    "mikiluru",
    "mikirulu",
    "mikiruru",
    "mildaunegeux",
    "mimas",
    "mimic",
    "mimic jester",
    "mimic king",
    "mimic mage",
    "minaruja",
    "minax bugard",
    "mind hoarder",
    "mingyi",
    "minhocao",
    "mint custard",
    "mired alfard",
    "mired cerberus",
    "mired hydra",
    "mired khimaira",
    "mired khrysokhimaira",
    "mired mantis",
    "mired orthrus",
    "mirka",
    "mischievous micholas",
    "miser murphy",
    "mithraslaver debhabob",
    "mligni-vorgut",
    "mobpix mucousmouth",
    "mocking colibri",
    "modron",
    "modron's druid",
    "moki",
    "mokkurkalfi",
    "mokumokuren",
    "molted mantis",
    "molten clot",
    "moltenox stubthumbs",
    "moly",
    "moo ouzi the swiftblade",
    "morbid molasses",
    "morblox chubbychin",
    "morbolger",
    "morgmox moldnoggin",
    "morille mortelle",
    "morion worm",
    "morseiu",
    "morta",
    "mortilox wartpaws",
    "moshdahn",
    "mother globe",
    "mountain worm",
    "mouu the waverider",
    "movamuq",
    "moxnix nightgoggle",
    "mu'gha legionkiller",
    "mu'nhi thimbletail",
    "mucoid mass",
    "muq shabeel",
    "murderous mandragora",
    "murk-veined baneberry",
    "murkmoan umbril",
    "muscaliet",
    "muu febi the steadfast",
    "muut",
    "muut's hound warrior",
    "muut's sacrifice",
    "mx'ghrah",
    "mycophile",
    "myin",
    "myradrosh",
    "myrmecoleon",
    "myrmeleontide",
    "mysticmaker profblix",
    "mythril mouth monamaq",
    "na'hya floodmaker",
    "naa yixo the stillrage",
    "naa zeku the unwaiting",
    "naga raja",
    "namorodo",
    "namtar",
    "nandi",
    "nanoplasm",
    "nant'ina",
    "naphula",
    "naphula's corpselight",
    "narasimha",
    "nargun",
    "nasus",
    "natrix",
    "ne",
    "neak",
    "necroplasm",
    "nee huxa the judgmental",
    "nehebkau",
    "neith",
    "neoingurgitator",
    "nepionic soulflayer",
    "nerrivik",
    "nguruvilu",
    "ni'ghu nestfender",
    "ni'zho bladebender",
    "nidhogg",
    "nightmare vase",
    "nightshade",
    "nihniknoovi",
    "nikilulu",
    "ningishzida",
    "nio-a",
    "nio-hum",
    "nis puk",
    "no'mho crimsonarmor",
    "noble mold",
    "nocuous inferno",
    "nocuous weapon",
    "nommo",
    "nonno",
    "northern shadow",
    "nosferatu",
    "nosferatu bats",
    "nosferatu murk",
    "nosferatu wolf",
    "nosoi",
    "novv the whitehearted",
    "npfundlwa",
    "nu'bhi spiraleye",
    "nue",
    "nuhn",
    "numbing blossom",
    "numbing norman",
    "nunyenunc",
    "nunyunuwi",
    "nussknacker",
    "nutmeg custard",
    "nympha eunomia",
    "ob",
    "observant zekka",
    "occidentalis shadow",
    "ocean sahagin",
    "ocythoe",
    "odqan",
    "ogama",
    "ogbunabali",
    "ogopogo",
    "ogygos",
    "okyupete",
    "old professor mariselle",
    "old sabertooth",
    "old shuck",
    "old two-wings",
    "olgoi-khorkhoi",
    "olla grande",
    "olla media",
    "olla pequena",
    "om'yovra",
    "one-eyed gwajboj",
    "oni carcass",
    "onryo",
    "onycophora's sandworm",
    "ophanim",
    "ophion",
    "orcfeltrap",
    "orcish bloodletter",
    "orcish hexspinner",
    "orcish overlord",
    "orcish panzer",
    "orcish warlord",
    "orctrap",
    "orcus",
    "orientalis shadow",
    "orna",
    "orthrus",
    "oryx",
    "ose",
    "osschaart's bat",
    "otherworldly rimester",
    "oupire",
    "ouryu",
    "ouzelum",
    "overlord bakgodek",
    "overlord's tombstone",
    "overseer",
    "ovni",
    "owl guardian",
    "padfoot",
    "pahh the gullcaller",
    "pakecet",
    "pakecet's pugil",
    "palila's vulture",
    "pallas",
    "pallid percy",
    "pandemonium warden",
    "pantagruel",
    "pantokrator",
    "panzer percival",
    "para",
    "paramount botulus",
    "paramount gallu",
    "paramount harpeia",
    "paramount ironclad",
    "paramount mantis",
    "paramount naraka",
    "pardus",
    "pascerpot",
    "patripatan",
    "pavan",
    "pazuzu",
    "peallaidh",
    "peaseblossom",
    "peerifool",
    "peg powler",
    "peirithoos",
    "pekapeka",
    "pelican",
    "peon pounder",
    "pernicious pachypodium",
    "petro pukis",
    "phanduron the condemned",
    "phantom worm",
    "piasa",
    "picklix longindex",
    "picolaton",
    "pignonpausard",
    "pil",
    "pixie impaler",
    "pixietrap",
    "plague chigoe",
    "plodding funguar",
    "podarge",
    "poison pukis",
    "poisonhand gnadgad",
    "polevik",
    "polybotes",
    "ponderer",
    "poroggo dom juan",
    "porphyrion",
    "portia",
    "powderer penny",
    "powderkeg yanadahn",
    "prankster maverix",
    "precipice vulture",
    "preening tulfaire",
    "prickly pitriv",
    "prickly sheep",
    "primordial pugil",
    "prince orobas",
    "prince seere",
    "princeps iv-xlv",
    "princeps xiii-lxxxix",
    "princess pudding",
    "proconsul xii",
    "procreator",
    "procrustean draugar",
    "procrustes",
    "promathia",
    "propagator",
    "prosperous luckybug",
    "proteus",
    "prototype eye",
    "provoker",
    "prowlox barrelbelly",
    "pruina",
    "pteranodon",
    "puca",
    "pudding",
    "pulverized pfeffer",
    "pungent fungus",
    "pungent ovim",
    "pungent patricia",
    "puretos",
    "purpleflash brukdok",
    "pustule",
    "putrid funguar",
    "puu timu the phantasmal",
    "pyre bat",
    "pyuu the spatemaker",
    "qilin",
    "qing long",
    "qn'zdei",
    "qoofim",
    "qu'pho bloodspiller",
    "qu'vho deathhurler",
    "quagmire pugil",
    "quasimodo",
    "queen crawler",
    "queen of batons",
    "queen of coins",
    "queen of cups",
    "queen of swords",
    "quetzalcoatl",
    "quetzalli",
    "quicktrix hexhands",
    "quiebitiel",
    "qull the shellbuster",
    "quu domi the gallant",
    "quu xijo the illusory",
    "ra'dha scarscute",
    "ra'gho darkfount",
    "ragelise",
    "raidne",
    "raja",
    "raker bee",
    "rakshas",
    "rambukk",
    "rampaging ram",
    "ramponneau",
    "rancor torch",
    "rani",
    "raptor nightstalker",
    "raskovnik",
    "ratatoskr",
    "ravager chariot",
    "ravenous crawler",
    "ravin raven",
    "ravishing rafflesia",
    "reacton",
    "reapertongue gadgquok",
    "rearguard eye",
    "ree nata the melomanic",
    "refitted chariot",
    "regicidal dullahan",
    "rencounter chariot",
    "renfred",
    "resheph",
    "resilient colibri",
    "revetaur",
    "rhoikos",
    "rhoitos",
    "roc",
    "rogue receptacle",
    "rohemolipaud",
    "rojgnoj's left hand",
    "rojgnoj's right hand",
    "roly-poly",
    "rose garden",
    "routsix rubbertendon",
    "ru'aern",
    "rubicund adenium",
    "ruby quadav",
    "ruea",
    "ruebezahl",
    "ruffbix jumbolobes",
    "rugaroo",
    "rukh",
    "ruminator",
    "rummager beetle",
    "rutrix hamgams",
    "rw nw prt m hrw",
    "ryy qihi the idolrobber",
    "sa'nha soulsaver",
    "saa doyi the fervid",
    "sabotender bailarin",
    "sabotender bailarina",
    "sabotender campeador",
    "sabotender corrido",
    "sabotender enamorado",
    "sabotender mariachi",
    "sabotender mercenario",
    "sabotender royal",
    "sacrificial goblet",
    "sagittarius x-xiii",
    "salamander",
    "sallow seymour",
    "saltopus",
    "sandworm",
    "sang buaya",
    "sanguine sapsucker",
    "sappy sycamore",
    "sarama",
    "sarameya",
    "sarbaz",
    "sarcophilus",
    "sarcopsylla",
    "sargas",
    "sarimanok",
    "sarsaok",
    "satellite claymores",
    "satellite daggers",
    "satellite great axes",
    "satellite guns",
    "satellite hammers",
    "satellite horns",
    "satellite knuckles",
    "satellite kunai",
    "satellite longbows",
    "satellite longswords",
    "satellite scythes",
    "satellite shield",
    "satellite spears",
    "satellite staves",
    "satellite tabars",
    "satellite tachi",
    "satiator",
    "sava savanovic",
    "schah",
    "schah's ashva",
    "schah's bhata",
    "schah's gaja",
    "schah's mantri",
    "schah's ratha",
    "schorl umbril",
    "scitalis",
    "scolopendra",
    "scorched yanthu",
    "scourquix scaleskin",
    "scruffix shaggychest",
    "scrutinizer",
    "scylla",
    "sea hog",
    "sea horror",
    "sedna",
    "seed mandragora",
    "seiryu",
    "sekhmet",
    "selkit",
    "sempurne",
    "sengann",
    "sensual sandy",
    "seps",
    "septic boil",
    "sere stump",
    "serket",
    "serpopard ishtar",
    "serpopard ninlil",
    "serra",
    "sewer syrup",
    "seww the squidlimbed",
    "shadow eye",
    "shadow of rage",
    "shadowbreath",
    "shadowguard demon",
    "shah",
    "shamblix rottenheart",
    "shankha",
    "sharabha",
    "sharp-eared ropipi",
    "sharptusk raaz",
    "shatterskull mippdapp",
    "shaula",
    "shedu",
    "shen",
    "shen's filtrate",
    "shesha",
    "shielded chariot",
    "shieldtrap",
    "shii",
    "shikaree x",
    "shikaree x's rabbit",
    "shikaree z",
    "shikaree z's wyvern",
    "shikigami weapon",
    "shimmering tarichuk",
    "shinryu",
    "shisox widebrow",
    "shockmaw",
    "shoggoth",
    "shrewd hunter",
    "silk caterpillar",
    "silverhook",
    "simurgh",
    "sin",
    "sippoy",
    "siranpa-kamuy",
    "sirrush",
    "sisyphus",
    "sitke",
    "skeleton scuffler",
    "skewer sam",
    "skinmask ugghfogg",
    "skirling liger",
    "skirmish pephredo",
    "skogs fru",
    "skuld",
    "skull of envy",
    "skull of gluttony",
    "skull of greed",
    "skull of lust",
    "skull of pride",
    "skull of sloth",
    "skull of wrath",
    "skvader",
    "slave globe",
    "slendlix spindlethumb",
    "slinkix trufflesniff",
    "slippery sucker",
    "sluagh",
    "slumbering samwell",
    "slystix megapeepers",
    "smeltix thickhide",
    "smierc",
    "smok",
    "smothered schmidt",
    "snoll tzar",
    "snow maiden",
    "snowpaw rabbit",
    "snypestix eaglebeak",
    "so'gho adderhandler",
    "so'zho metalbender",
    "soaring dvergr",
    "soaring dweorg",
    "soaring kumakatok",
    "soaring naraka",
    "soaring strigoi",
    "sobek",
    "soiled funguar",
    "solicitor",
    "soo jopo the fiendking",
    "sordid lizard",
    "soulsender fugbrag",
    "soulstealer skullnix",
    "southern shadow",
    "sovereign behemoth",
    "sozu bliberry",
    "sozu rogberry",
    "sozu sarberry",
    "sozu terberry",
    "sparkspox sweatbrow",
    "specter worm",
    "spellspear djokvukk",
    "spinalsucker galflmall",
    "spiny spipi",
    "splacknuck",
    "stabnix skewerfinger",
    "stachysaurus",
    "startled uragnite",
    "statue prototype",
    "staumarth",
    "stcemqestcint",
    "steam cleaner",
    "steam spout",
    "steelbiter gudrud",
    "steelfleece baldarich",
    "steelshank kratzvatz",
    "steely weapon",
    "stihi",
    "stinging sophie",
    "stolas",
    "stray",
    "stray mary",
    "stringes",
    "strix",
    "strophadia",
    "stubborn dredvodd",
    "sturm",
    "sturmtiger",
    "sugaar",
    "sunderclaw",
    "suparna",
    "suparna fledgling",
    "supernal chapuli",
    "supplespine mujwuj",
    "surly craklaw",
    "suspended sculpture",
    "suttung",
    "suu xicu the cantabile",
    "suzaku",
    "swamfisk",
    "swashstox beadblinker",
    "swift hunter",
    "swipostik",
    "sword sorcerer solisoq",
    "swypestix tigershins",
    "ta'hyu gallanthunter",
    "tablilla",
    "taelmoth the diremaw",
    "taifun",
    "taisaijin",
    "tammuz",
    "tangaroa",
    "tangata manu",
    "tapana",
    "tapana's minion",
    "taquede",
    "tarasque",
    "tartalo",
    "taruroaster biggsjig",
    "taweret",
    "tawny-fingered mugberry",
    "tax'et",
    "taxim",
    "te'zha ironclad",
    "tee zaksa the ceaseless",
    "teekesselchen",
    "tefenet",
    "tegmine",
    "tejas",
    "teles",
    "tempest tigon",
    "tenacious panopt",
    "tenodera",
    "tenzen",
    "teporingo",
    "territorial lucerewe",
    "tethra",
    "teugghia",
    "thoon",
    "thousandarm deshglesh",
    "three-eyed prozpuz",
    "thu'ban",
    "thunder elemental",
    "thunder gremlin",
    "thunderclaw thuban",
    "thunor",
    "tiamat",
    "ticktox beadyeyes",
    "tiffenotte",
    "tigerbane bakdak",
    "tikbalang",
    "time bomb",
    "timeworn warrior",
    "tinnin",
    "tipha",
    "titlacauan",
    "tocktix thinlids",
    "tococo",
    "tolba",
    "tom tit tat",
    "tombstone prototype",
    "tonberry decapitator",
    "tonberry kinq",
    "tonberry lieje",
    "tonberry pontifex",
    "tonberry tracker",
    "toppling tuber",
    "tottering toby",
    "toxic tamlyn",
    "trailblix goatmug",
    "transcendent scorpion",
    "treble noctules",
    "trembler tabitha",
    "tres duendes",
    "triarius iv-xiv",
    "triarius x-xv",
    "triarius xiii-lix",
    "tribunus vii-i",
    "trickster kinetix",
    "trikotrak",
    "tristitia",
    "trna",
    "trombe",
    "trompe l'oeil",
    "tros",
    "truculent mantis",
    "trudging thomas",
    "tsuchigumo",
    "tsui-goab",
    "tufflix loglimbs",
    "tumbling truffle",
    "tunga",
    "turul",
    "tuskertrap",
    "tutewehiwehi",
    "two-faced flan",
    "tyger",
    "tymexox ninefingers",
    "tyrannic tunnok",
    "tyrant",
    "tzee xicu idol",
    "tzee xicu the manifest",
    "ubume",
    "ul'yovra",
    "ulhuadshi",
    "ullikummi",
    "ultrasonic zeknajak",
    "umberwood tiger",
    "umdhlebi",
    "undaunted colibri",
    "undead crab",
    "undead leech",
    "undead slime",
    "undead toad",
    "underwood eruca",
    "ungur",
    "unstable cluster",
    "unut",
    "upas-kamuy",
    "uprooted sapling",
    "uptala",
    "upyri",
    "urayuli",
    "urd",
    "urmahlullu",
    "ushumgal",
    "usurper",
    "utgarth bat",
    "utgarth bats",
    "va'gho bloodbasked",
    "va'rhu bodysnatcher",
    "va'zhe pummelsong",
    "vaa huja the erudite",
    "vadleany",
    "valkeng",
    "valkurm emperor",
    "valor",
    "vampyr bats",
    "vampyr dog",
    "vampyr wolf",
    "vanasarvik",
    "vanguard eye",
    "vanilla custard",
    "vanquished einherjar",
    "varanus",
    "varkolak",
    "vasuki",
    "vedrfolnir",
    "vee ladu the titterer",
    "vegnix greenthumb",
    "veiled amphiptere",
    "veiled gigaworm",
    "veiled ironclad",
    "veiled ixion",
    "veiled sanguiptere",
    "velionis",
    "velkk sentinel",
    "velosareon",
    "vengeful shunned",
    "venomfang",
    "verdelet",
    "veri selen",
    "vermillion fishfly",
    "verthandi",
    "vetehinen",
    "vidala",
    "vidmapire",
    "vigilant gear",
    "vigilant gears",
    "vinipata",
    "vinipata's naraka",
    "vir'ava",
    "vir'ava's rafflesia",
    "virvatuli",
    "viscount morax",
    "vodyanoi",
    "void hare",
    "voidstreaker butchnotch",
    "voidwrought",
    "voirloup",
    "volatile cluster",
    "voll the sharkfinned",
    "voluptuous vilma",
    "voluptuous vivian",
    "voso",
    "vouivre",
    "vrtra",
    "vulkodlac",
    "vulpangue",
    "vuu puqu the beguiler",
    "vyala",
    "wailer",
    "wake warder wanda",
    "wandering ghost",
    "warabouc",
    "waraxe beak",
    "warblade beak",
    "warbler",
    "warchief tombstone",
    "warchief vatgit",
    "warder of courage",
    "warder of dignity",
    "warder of faith",
    "warder of fortitude",
    "warder of hope",
    "warder of justice",
    "warder of love",
    "warder of loyalty",
    "warder of mercy",
    "warder of prudence",
    "warder of temperance",
    "warder's ghrah",
    "warder's phuabo",
    "warder's xzomit",
    "warlord rojgnoj",
    "wasabix callusdigit",
    "wasserspeier",
    "watch hippogryph",
    "water elemental",
    "waugyl",
    "wazir",
    "weeping willow",
    "wepwawet",
    "western shadow",
    "wetlands orobon",
    "wherwetrice",
    "whiro",
    "whistrix toadthroat",
    "white coney",
    "wildfire",
    "wilywox tenderpalm",
    "wind pukis",
    "wivre cragdweller",
    "woodland sage",
    "woodnix shrillwhistle",
    "woodtroll elite guard",
    "woodtroll mirror guard",
    "worr the clawfisted",
    "wounded wurfel",
    "wraithdancer gidbnod",
    "wrathare",
    "wulgaru",
    "wurdalak",
    "wuu qoho the razorclaw",
    "wuur the sandcomber",
    "wyrmfly",
    "wyrmgnasher bjakdek",
    "wyrmwix snakespecs",
    "wyvernhunter bambrox",
    "wyvernpoacher drachlox",
    "xaa chau the roctalon",
    "xan",
    "xhoo fuza the sublime",
    "xibalba",
    "xolotl",
    "xoo kaza the solemn",
    "xuan wu",
    "xuu bhoqa the enigma",
    "yaa haqa the profane",
    "yaanei",
    "yacumama",
    "yaguarogui",
    "yagudo avatar",
    "yagudo high priest",
    "yagudo templar",
    "yahhta",
    "yal-un eke",
    "yang",
    "yara ma yha who",
    "yarr the pearleyed",
    "yatagarasu",
    "yearner",
    "yilan",
    "yilan's dragon",
    "yilbegan",
    "ying",
    "yowie",
    "yum kimil",
    "yuu mjuu the awakened",
    "za'dha adamantking",
    "zagh",
    "zareehkl the jubilant",
    "zduhac",
    "ze'vho fallsplitter",
    "zebra zachary",
    "zeid",
    "zerde",
    "zerde's drisheen",
    "zerde's haupia",
    "zerde's kacamak",
    "zhu que",
    "zhuu buxu the silent",
    "zi'ghi boneeater",
    "zikko",
    "zipacna",
    "ziphius",
    "zirnitra",
    "zizzy zillah",
    "zmag ognjeni vuk",
    "zmey gorynych",
    "zo'khu blackcloud",
    "zo'pha forgesoul",
    "zoraal ja's pkuucha",
    "zoredonite",
    "zurko-bazurko",
    "zuug the shoreleaper",
    "zvahl fortalice",
};
static const int g_nmNameCount = 2132;

#endif
